######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : harry-potter-text-analysis, Index = 0, Count = null
# SUBMIT FILE NAME : register_local_2_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=eb15ce68-d76b-416d-8f6e-2a9d7dbb9efa PEGASUS_WF_LABEL=harry-potter-text-analysis PEGASUS_DAG_JOB_ID=register_local_2_0 PEGASUS_SITE=local"
arguments = " -n pegasus::rc-client -N null -R local  -L harry-potter-text-analysis -T 2020-08-10T06:36:30+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-rc-client --prefix pegasus.catalog.replica.output --conf /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0002/pegasus.8258500132211400458.properties -v --meta /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0002/00/00/plot_ID0000003.meta --insert /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0002/00/00/register_local_2_0.in"
error = /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0002//00/00/register_local_2_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
log = /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0002/harry-potter-text-analysis-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0002//00/00/register_local_2_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 60
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "eb15ce68-d76b-416d-8f6e-2a9d7dbb9efa"
+pegasus_wf_uuid = "eb15ce68-d76b-416d-8f6e-2a9d7dbb9efa"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "harry-potter-text-analysis-0"
+pegasus_wf_time = "20200810T063633+0000"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local_2_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
